it('should have the right text in the headline', () => {
  cy.visit('/property-1.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/property-2.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/property-3.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/properties-2.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/properties-3.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/register.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/contact-2.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/contact-3.html');
  cy.userwayAnalysis({screenshots: true});
  cy.visit('/single.html');
  cy.userwayAnalysis({screenshots: true});
});
